jobs:
  test:
    name: JDK ${{ matrix.java }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Cancel previous runs
      uses: styfle/cancel-workflow-action@85880fa0301c86cca9da44039ee3bb12d3bedbfa
      with:
        access_token: ${{ github.token }}
    - continue-on-error: true
      name: Check out repository
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        cache: maven
        distribution: zulu
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Install
      run: mvn -B -U install clean --fail-never --quiet -DskipTests=true -Dinvoker.skip=true
      shell: bash
    - continue-on-error: true
      name: Test
      run: mvn -B verify
      shell: bash
    strategy:
      matrix:
        java:
        - 8
        - 11
        - 17
        - 21
name: CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
